project:
  type: website
  output-dir: docs

website:
  title: "Spatial Planning @ UQ"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: _shinyplanr_
        href: shinyplanr.qmd
      - text: Deployments
        menu:
          - text: Weddell Sea
            href: realTime/WeddellSea.qmd
          - text: Kosrae
            href: realTime/Kosrae.qmd
      - text: Planning Aspects
        href: elements.qmd
      - text: Other Tools
        href: shiny.qmd
      - text: Publications
        href: publications.qmd
      - text: Our Services
        href: services.qmd
        
    # your social media handles
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:a.richardson1@uq.edu.au"
      - icon: github
        href: https://github.com/SpatialPlanning
        target: _blank

      
  page-footer:
    center: "This page is built with [Quarto](https://quarto.org/)."
    left:  "&copy; Website Dr Jason D. Everett 2025"
    right: |
      <span class="faux-block"><a href="https://github.com/SpatialPlanning/SpatialPlanning.github.io" target="_blank">View source on GitHub</a></span>

resources: 
    - "data/*"

format:
  html:
    # theme: cosmo
    theme: spacelab
    # theme: yeti
    css: styles.css
    toc: true
    toc-depth: 2
    toc-expand: 2
    toc-location: right
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-icon: true

editor: source
page-layout: full
lightbox: true

