project:
  type: website
  output-dir: docs

website:
  # favicon: "HexSticker/logo_LR.png"
  # announcement:
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Register for our upcoming Winter 2025 Workshops**. Register [here](https://payments.uq.edu.au/CBCS_R_workshop) or see below for further information about dates and topics covered."
  #   type: warning
  #   position: below-navbar
  # announcement: 
  #   icon: info-circle
  #   dismissable: false
  #   content: "**NOTE: We are having some issues with the registration portal. It will be open again shortly. Please check back regularly if you still want to register. There is still time and space!**" 
  #   type: danger
  #   position: below-navbar
    
  # page-navigation: true
  title: "Spatial Planning Team @ UQ"
  # sidebar:
    # logo: "HexSticker/logo_LR.png"
    # pinned: true
    # align: center
    # tools:
    # - icon: globe
    #   href: https://openscapes.org
    #   text: "Openscapes.org"
    # - icon: github
    #   href: https://github.com/openscapes/quarto-website-tutorial
    #   text: "Quarto website tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: realTime.qmd
        text: Real-time Planning
      - href: spatialPlanning.qmd
        text: Planning Solutions
      - href: climate.qmd
        text: Climate-smart Tools
      - href: shiny.qmd
        text: Our Shiny Tools
      - href: publications.qmd
        text: Publications
      # - href: contact.qmd
        # text: Contact
      
  page-footer:
    center: "This page is built with [Quarto](https://quarto.org/)."
    left:  "&copy; Website Dr Jason D. Everett 2025"

resources: 
    - "data/*"

format:
  html:
    # theme: cosmo
    # theme: spacelab
    theme: yeti
    css: styles.css
    toc: true
    toc-depth: 2
    toc-expand: 2
    toc-location: right
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-icon: true

editor: source

lightbox: true

