---
title: "Challenges in spatial planning"
---

Accelerating human activities and intensifying climate change and are threatening biodiversity. In response, countries are scaling-up spatial planning to meet targets under the Global Biodiversity Framework—expanding spatial planning (Target 1), restoring ecosystems (Target 2), and conserving biodiversity (Target 3). But planning is complex. Each nation has unique requirements, and stakeholder processes are often slow and gridlocked, hindered by a disconnect between planning tools and stakeholder needs.

## Who we are

We are a team of university researchers advancing spatial planning for real-world conservation. Our mission is to support biodiversity outcomes through transparent, cutting-edge tools tailored to local contexts. We co-develop planning solutions with partners, continually improving our open-source platform shinyplanr based on user feedback and emerging science.

## Our expertise
- Prof. Anthony J. Richardson – A mathematical ecologist with 25+ years of research experience in climate change ecology, ecosystem modelling, and conservation science.

- A/Prof. Daniel Dunn – A marine conservation scientist with 20+ years advising on area-based management for international bodies including UNESCO, the International Seabed Authority (ISA), the Convention on Biological Diversity (CBD), the Convention on Migratory Species (CMS), the Commission for the Conservation of Antarctic Marine Living Resources (CCAMLR), and the Biodiversity Beyond National Jurisdiction (BBNJ) treaty.

- Dr Jason Everett – A spatial ecologist and data scientist developing tools for designing protected areas and analysing climate change impacts on ecosystems.

## Advancing spatial planning for Biodiversity and climate resilience

This website showcases our research-driven tools – particularly shinyplanr - and expertise for developing rapid, effective and inclusive spatial plans. We focus on co-designed solutions that support biodiversity conservation, restoration, and sustainable ocean use under a changing climate.


